### PR TITLE
Set m_bSwizzleChannels codec parameter based on srcBufferType

### LINKED ISSUE #59: Incorrect default channel swizzle for DXTC codec
I'm running some 32-bit RGBA texture data through the Compressonator library using the high-level `CMP_ConvertTexture()` API, and I noticed that while the output looks correct if I choose `CMP_FORMAT_BC7` as the output format, choosing `CMP_FORMAT_BC1` or `CMP_FORMAT_BC3` results in the red and blue channels swapped in the output, using otherwise identical input data and compression settings.

I dug around a bit and found an `m_bSwizzleChannels` variable that controls whether the input data is treated as BGRA (the default) or RGBA. I see no corresponding option in `CMP_CompressOptions` to change this value, aside from using the (largely undocumented) `CmdSet` array to set "SwizzleChannels" to a non-zero value. But, shouldn't the default be determined based on the src texture format -- if it's `CMP_FORMAT_RGBA_*`, shouldn't `m_bSwizzleChannels` automatically default to true instead of false?

### PR DESCRIPTION
**Pull request by cdwfs**
Fixes #59

### CODE REVIEW

**Comment by cdwfs** [comment]
I'm not sure if this is sufficient for all cases, but it's fixed all my use cases. Is there a test suite I can run to make sure I haven't accidentally broken anything?

Of course I welcome any feedback :)

**Comment by NPCompress** [comment]
@cdwfs Nice work. We will do an internal test them make the commit to master.

Thanks for your support.

File: Compressonator/Source/Compress.cpp [hunk 1]
```diff
@@ -687,6 +687,18 @@ CMP_ERROR ThreadedCompressTexture(const CMP_Texture* pSourceTexture, CMP_Texture
...
 
         CodecBufferType srcBufferType = GetCodecBufferType(pSourceTexture->format);
+        if (NeedSwizzle(pDestTexture->format))
+        {
+            bool swizzleSrcBuffer = true;
+            switch (srcBufferType)
+            {
+            case CBT_BGRA8888:
+            case CBT_BGR888:
+                swizzleSrcBuffer = true;
```
Comment (cdwfs) [inline Compressonator/Source/Compress.cpp]: Oops, copy/paste error; this should be false. Fixing presently!
